@startuml
skinparam linetype ortho


node "Workflow 'eoap-api'" {
    component "eoap-api" as eoap_api {
    
        portin "stac_api_endpoint" as eoap_api_stac_api_endpoint
    
        portin "search_request" as eoap_api_search_request
    
        portin "processes_api_endpoint" as eoap_api_processes_api_endpoint
    
        portin "execute_request" as eoap_api_execute_request
    
    
        portout "search_output" as eoap_api_search_output
    
        portout "process_output" as eoap_api_process_output
    
    }


    component "discovery" as eoap_api_discovery {
    
        portin "api_endpoint" as eoap_api_discovery_api_endpoint
        eoap_api_stac_api_endpoint .down.> eoap_api_discovery_api_endpoint
    
        portin "search_request" as eoap_api_discovery_search_request
        eoap_api_search_request .down.> eoap_api_discovery_search_request
    

    
        portout "search_output" as eoap_api_discovery_search_output
    
    }

    component "processes" as eoap_api_processes {
    
        portin "api_endpoint" as eoap_api_processes_api_endpoint
        eoap_api_processes_api_endpoint .down.> eoap_api_processes_api_endpoint
    
        portin "execute_request" as eoap_api_processes_execute_request
        eoap_api_execute_request .down.> eoap_api_processes_execute_request
    
        portin "search_results" as eoap_api_processes_search_results
        eoap_api_discovery_search_output .down.> eoap_api_processes_search_results
    

    
        portout "process_output" as eoap_api_processes_process_output
    
    }

}

node "CommandLineTool 'stac-client'" {
    component "stac-client" as stac_client {
    
        portin "api_endpoint" as stac_client_api_endpoint
    
        portin "search_request" as stac_client_search_request
    
    
        portout "search_output" as stac_client_search_output
    
    }


}

node "CommandLineTool 'ogc-api-processes-client'" {
    component "ogc-api-processes-client" as ogc_api_processes_client {
    
        portin "api_endpoint" as ogc_api_processes_client_api_endpoint
    
        portin "execute_request" as ogc_api_processes_client_execute_request
    
        portin "search_results" as ogc_api_processes_client_search_results
    
    
        portout "process_output" as ogc_api_processes_client_process_output
    
    }


}



    
        
eoap_api_discovery_search_output .up.> eoap_api_search_output
        
    
        
eoap_api_processes_process_output .up.> eoap_api_process_output
        
    

    
eoap_api_discovery .right.> stac_client
    
eoap_api_processes .right.> ogc_api_processes_client
    

    
        
    

    

    
        
    

    

@enduml