@startuml
autonumber "<b>[000]"

{% for workflow in workflows %}
{% if 'Workflow' == workflow.class_ %}
box "{{ workflow.id }}"
    control "{{ workflow.id }}" as {{ workflow.id | to_puml_name }}_or

    {% if workflow.steps %}
        {% for step in workflow.steps %}
    participant {{ step.id | to_puml_name }}
        {% endfor %}
    {% endif %}
end box

activate {{ workflow.id | to_puml_name }}_or

{% for input in workflow.inputs %}
-> {{ workflow.id | to_puml_name }}_or : {{ input.id }}
{% if input.label %}note top
{{ input.label }}
end note{% endif %}
{% endfor %}

{% for output in workflow.outputs %}
<-- {{ workflow.id | to_puml_name }}_or : {{ output.id }}
{% if output.label %}note top
{{ output.label }}
end note{% endif %}
{% endfor %}

{% endif %}
{% endfor %}

@enduml
